//! Static icon-key compatibility, with a bounded native picker model.
use crate::FavoriteIconChoice;
use slint::{ModelRc, VecModel};
use std::rc::Rc;
const KEYS: &[(&str, &str)] = &[
    ("none", "No icon"),
    ("Mail", "Mail"),
    ("Phone", "Phone"),
    ("MapPin", "Map Pin"),
    ("Terminal", "Terminal"),
    ("Code", "Code"),
    ("Link", "Link"),
    ("File", "File"),
    ("Folder", "Folder"),
    ("Document", "Document"),
    ("Clipboard", "Clipboard"),
    ("Star", "Star"),
    ("Tag", "Tag"),
    ("Key", "Key"),
    ("Calendar", "Calendar"),
    ("User", "User"),
    ("Home", "Home"),
    ("Suitcase", "Suitcase"),
    ("AddMember", "Add Member"),
    ("AddSources", "Add Sources"),
    ("Agent", "Agent"),
    ("AgentMode", "Agent Mode"),
    ("AllGizmos", "All Gizmos"),
    ("AllProductsExplore", "All Products Explore"),
    ("Analytics", "Analytics"),
    ("AnalyzeData", "Analyze Data"),
    ("ApiKey", "Api Key"),
    ("ApiKeyAdmin", "Api Key Admin"),
    ("ApiKeyServiceAccount", "Api Key Service Account"),
    ("ApiKeys", "Api Keys"),
    ("Archive", "Archive"),
    ("Array", "Array"),
    ("ArrowBottomLeftSm", "Arrow Bottom Left Sm"),
    ("ArrowBottomRightSm", "Arrow Bottom Right Sm"),
    ("ArrowCurved", "Arrow Curved"),
    ("ArrowCurvedLeft", "Arrow Curved Left"),
    ("ArrowCurvedRight", "Arrow Curved Right"),
    ("ArrowCurvedRightXs", "Arrow Curved Right Xs"),
    ("ArrowCurvedRightXs24px", "Arrow Curved Right Xs24px"),
    ("ArrowDown", "Arrow Down"),
    ("ArrowDownLg", "Arrow Down Lg"),
    ("ArrowDownSm", "Arrow Down Sm"),
    ("ArrowLeft", "Arrow Left"),
    ("ArrowLeftLg", "Arrow Left Lg"),
    ("ArrowLeftSm", "Arrow Left Sm"),
    ("ArrowRight", "Arrow Right"),
    ("ArrowRightLg", "Arrow Right Lg"),
    ("ArrowRightSm", "Arrow Right Sm"),
    ("ArrowRotateCcw", "Arrow Rotate Ccw"),
    ("ArrowRotateCw", "Arrow Rotate Cw"),
    ("ArrowTopLeftSm", "Arrow Top Left Sm"),
    ("ArrowTopRightSm", "Arrow Top Right Sm"),
    ("ArrowUp", "Arrow Up"),
    ("ArrowUpLg", "Arrow Up Lg"),
    ("ArrowUpRight", "Arrow Up Right"),
    ("ArrowUpSm", "Arrow Up Sm"),
    ("AspectRatio11", "Aspect Ratio11"),
    ("AspectRatio169", "Aspect Ratio169"),
    ("AspectRatio34", "Aspect Ratio34"),
    ("AspectRatio43", "Aspect Ratio43"),
    ("AspectRatio916", "Aspect Ratio916"),
    ("Assistant", "Assistant"),
    ("Astronout", "Astronout"),
    ("AtSign", "At Sign"),
    ("Atom", "Atom"),
    ("AutoPairApps", "Auto Pair Apps"),
    ("AutoSuggestedEdits", "Auto Suggested Edits"),
    ("Autocomplete", "Autocomplete"),
    ("AvatarFilledProfile", "Avatar Filled Profile"),
    ("AvatarProfile", "Avatar Profile"),
    ("Back10s", "Back10s"),
    ("Back15s", "Back15s"),
    ("BackLarge", "Back Large"),
    ("BackSmall", "Back Small"),
    ("BackToApp", "Back To App"),
    ("BackgroundConversation", "Background Conversation"),
    ("BalancingScale", "Balancing Scale"),
    ("BarChart", "Bar Chart"),
    ("BarChartFilled", "Bar Chart Filled"),
    ("Batch", "Batch"),
    ("Batches", "Batches"),
    ("Bell", "Bell"),
    ("BellFilled", "Bell Filled"),
    ("Beta", "Beta"),
    ("Bills", "Bills"),
    ("Blend", "Blend"),
    ("BlendingCurveSharp", "Blending Curve Sharp"),
    ("BlendingCurveSmooth", "Blending Curve Smooth"),
    ("BlendingCurveSubtle", "Blending Curve Subtle"),
    ("Bolt", "Bolt"),
    ("Book", "Book"),
    ("BookBookmark", "Book Bookmark"),
    ("BookClock", "Book Clock"),
    ("BookClosed", "Book Closed"),
    ("BookOpen", "Book Open"),
    ("BookWrench", "Book Wrench"),
    ("Boolean", "Boolean"),
    ("Brain", "Brain"),
    ("Branch", "Branch"),
    ("BranchAlt", "Branch Alt"),
    ("Bug", "Bug"),
    ("BuilderProfileCard", "Builder Profile Card"),
    ("BuildingWorkspace", "Building Workspace"),
    ("Business", "Business"),
    ("BusinessFilled", "Business Filled"),
    ("Cabinet", "Cabinet"),
    ("CalendarAlt", "Calendar Alt"),
    ("CalendarToday", "Calendar Today"),
    ("Camera", "Camera"),
    ("CameraFilledPhoto", "Camera Filled Photo"),
    ("CameraPhoto", "Camera Photo"),
    ("CaptionCcOff", "Caption Cc Off"),
    ("CaptionCcOn", "Caption Cc On"),
    ("CaptionOff", "Caption Off"),
    ("CaptionOn", "Caption On"),
    ("Card", "Card"),
    ("CaretDown", "Caret Down"),
    ("CaretLeft", "Caret Left"),
    ("CaretRight", "Caret Right"),
    ("CaretUp", "Caret Up"),
    ("Category", "Category"),
    ("Certificate", "Certificate"),
    ("Chart", "Chart"),
    ("ChartXAxis", "Chart XAxis"),
    ("ChartYAxis", "Chart YAxis"),
    ("Chat", "Chat"),
    ("ChatCompose", "Chat Compose"),
    ("ChatDashedCheckedTemp", "Chat Dashed Checked Temp"),
    ("ChatDashedTemp", "Chat Dashed Temp"),
    ("ChatTemporary", "Chat Temporary"),
    ("ChatTripleDots", "Chat Triple Dots"),
    ("Chats", "Chats"),
    ("Check", "Check"),
    ("CheckCircle", "Check Circle"),
    ("CheckCircleDashed", "Check Circle Dashed"),
    ("CheckCircleFilled", "Check Circle Filled"),
    ("CheckLg", "Check Lg"),
    ("CheckMd", "Check Md"),
    ("ChevronDown", "Chevron Down"),
    ("ChevronDownLg", "Chevron Down Lg"),
    ("ChevronDownMd", "Chevron Down Md"),
    ("ChevronDownUp", "Chevron Down Up"),
    ("ChevronDownVector", "Chevron Down Vector"),
    ("ChevronLeft", "Chevron Left"),
    ("ChevronLeftLg", "Chevron Left Lg"),
    ("ChevronLeftMd", "Chevron Left Md"),
    ("ChevronRight", "Chevron Right"),
    ("ChevronRightAlt", "Chevron Right Alt"),
    ("ChevronRightLg", "Chevron Right Lg"),
    ("ChevronRightMd", "Chevron Right Md"),
    ("ChevronSmallDown", "Chevron Small Down"),
    ("ChevronSmallLeft", "Chevron Small Left"),
    ("ChevronSmallRight", "Chevron Small Right"),
    ("ChevronSmallUp", "Chevron Small Up"),
    ("ChevronUp", "Chevron Up"),
    ("ChevronUpDown", "Chevron Up Down"),
    ("ChevronUpLg", "Chevron Up Lg"),
    ("ChevronUpMd", "Chevron Up Md"),
    ("Circle", "Circle"),
    ("CircleDashed", "Circle Dashed"),
    ("CircleQuestion", "Circle Question"),
    ("ClappingBoardClosed", "Clapping Board Closed"),
    ("ClappingBoardOpen", "Clapping Board Open"),
    ("Cleanup", "Cleanup"),
    ("Clear", "Clear"),
    ("Click", "Click"),
    ("Clip", "Clip"),
    ("ClipboardCopy", "Clipboard Copy"),
    ("Clock", "Clock"),
    ("Clock10s", "Clock10s"),
    ("Clock15s", "Clock15s"),
    ("Clock20s", "Clock20s"),
    ("Clock5s", "Clock5s"),
    ("ClockOff", "Clock Off"),
    ("CloseBold", "Close Bold"),
    ("CodeSquareSlash", "Code Square Slash"),
    ("Collapse", "Collapse"),
    ("CollapseLarge", "Collapse Large"),
    ("CollapseLeft", "Collapse Left"),
    ("CollapseLg", "Collapse Lg"),
    ("CollapseRight", "Collapse Right"),
    ("CollapseSm", "Collapse Sm"),
    ("CollapseSmall", "Collapse Small"),
    ("ColorTheme", "Color Theme"),
    ("Comment", "Comment"),
    ("Commit", "Commit"),
    ("Compare", "Compare"),
    ("CompareArrows", "Compare Arrows"),
    ("Compass", "Compass"),
    ("Complete", "Complete"),
    ("ComposeCanvasEditStar", "Compose Canvas Edit Star"),
    ("ComposeDashedTemporary", "Compose Dashed Temporary"),
    ("ComposeEditSquare", "Compose Edit Square"),
    ("Confetti", "Confetti"),
    ("ConfettiParty", "Confetti Party"),
    ("Connect", "Connect"),
    ("ConnectApps", "Connect Apps"),
    ("ConnectedDynamicGpt", "Connected Dynamic Gpt"),
    ("ConnectorsConnectedApps", "Connectors Connected Apps"),
    ("Copy", "Copy"),
    ("CreditCard", "Credit Card"),
    ("Credits", "Credits"),
    ("Cube", "Cube"),
    ("Cursor", "Cursor"),
    ("Customize", "Customize"),
    ("DarkMode", "Dark Mode"),
    ("DataControls", "Data Controls"),
    ("DeepSearchTelescope", "Deep Search Telescope"),
    ("Delete", "Delete"),
    ("DeleteAccount", "Delete Account"),
    ("Desktop", "Desktop"),
    ("DiningEvents", "Dining Events"),
    ("DisabledCursor", "Disabled Cursor"),
    ("Dock", "Dock"),
    ("Documentation", "Documentation"),
    ("DollarCircle", "Dollar Circle"),
    ("Dot", "Dot"),
    ("DotsHorizontal", "Dots Horizontal"),
    ("DotsHorizontalCircle", "Dots Horizontal Circle"),
    ("DotsHorizontalMoreMenu", "Dots Horizontal More Menu"),
    ("DotsVertical", "Dots Vertical"),
    ("DotsVerticalCircle", "Dots Vertical Circle"),
    ("DotsVerticalMoreMenu", "Dots Vertical More Menu"),
    ("DoubleChevronLeft", "Double Chevron Left"),
    ("DoubleChevronRight", "Double Chevron Right"),
    ("Download", "Download"),
    ("DownloadCircle", "Download Circle"),
    ("DownloadGifWatermark", "Download Gif Watermark"),
    ("DownloadSimple", "Download Simple"),
    ("DownloadVideo", "Download Video"),
    ("DownloadVideoWatermark", "Download Video Watermark"),
    ("Dropdown", "Dropdown"),
    ("DropdownVector", "Dropdown Vector"),
    ("Dumbbell", "Dumbbell"),
    ("EarthTravelWorld", "Earth Travel World"),
    ("Edit", "Edit"),
    ("EditAlt", "Edit Alt"),
    ("EditDalleImage", "Edit Dalle Image"),
    ("EditPencil", "Edit Pencil"),
    ("EditStar", "Edit Star"),
    ("EditXs", "Edit Xs"),
    ("Education", "Education"),
    ("Email", "Email"),
    ("EmojiAdd", "Emoji Add"),
    ("EmojiLists", "Emoji Lists"),
    ("EmojiRemove", "Emoji Remove"),
    ("EmojiSections", "Emoji Sections"),
    ("EmojiWords", "Emoji Words"),
    ("EmptyCircle", "Empty Circle"),
    ("EmptyCircleFilled", "Empty Circle Filled"),
    ("EnterLogin", "Enter Login"),
    ("Enum", "Enum"),
    ("Equal", "Equal"),
    ("Error", "Error"),
    ("ExclamationMarkCircle", "Exclamation Mark Circle"),
    ("ExitLogout", "Exit Logout"),
    ("Expand", "Expand"),
    ("ExpandLarge", "Expand Large"),
    ("ExpandLg", "Expand Lg"),
    ("ExpandMd", "Expand Md"),
    ("ExpandSm", "Expand Sm"),
    ("ExpandSmall", "Expand Small"),
    ("Explore", "Explore"),
    ("ExploreSora", "Explore Sora"),
    ("ExternalLink", "External Link"),
    ("Eye", "Eye"),
    ("EyeClosed", "Eye Closed"),
    ("EyeOff", "Eye Off"),
    ("FeaturedWreath", "Featured Wreath"),
    ("File3d", "File3d"),
    ("FileAudio", "File Audio"),
    ("FileBlank", "File Blank"),
    ("FileCode", "File Code"),
    ("FileDocument", "File Document"),
    ("FileImage", "File Image"),
    ("FilePresentation", "File Presentation"),
    ("FileSpreadsheet", "File Spreadsheet"),
    ("FileSpreedsheet", "File Spreedsheet"),
    ("FileUpload", "File Upload"),
    ("FileVideo", "File Video"),
    ("FileZip", "File Zip"),
    ("Filter", "Filter"),
    ("FineTuning", "Fine Tuning"),
    ("FistBump", "Fist Bump"),
    ("Flag", "Flag"),
    ("Flash", "Flash"),
    ("Flask", "Flask"),
    ("FlaskFilled", "Flask Filled"),
    ("FolderDocumentsFinder", "Folder Documents Finder"),
    ("FolderOpen", "Folder Open"),
    ("FolderPlus", "Folder Plus"),
    ("FolderPlusAdd", "Folder Plus Add"),
    ("FolderShared", "Folder Shared"),
    ("FolderSharedOpen", "Folder Shared Open"),
    ("FolderStuffed", "Folder Stuffed"),
    ("FolderUnshare", "Folder Unshare"),
    ("Folders", "Folders"),
    ("Followup", "Followup"),
    ("Forum", "Forum"),
    ("Forward", "Forward"),
    ("Forward10s", "Forward10s"),
    ("Forward15s", "Forward15s"),
    ("Frozen", "Frozen"),
    ("Function", "Function"),
    ("Functions", "Functions"),
    ("GenerateSuggestedEdits", "Generate Suggested Edits"),
    ("Glasses", "Glasses"),
    ("Globe", "Globe"),
    ("GlobeAltRealTimeSearch", "Globe Alt Real Time Search"),
    ("GlobeFilled", "Globe Filled"),
    ("GlobeOffRealTimeSearch", "Globe Off Real Time Search"),
    ("GlobeRealTimeSearch", "Globe Real Time Search"),
    ("GlobeSpin", "Globe Spin"),
    ("Go", "Go"),
    ("GoFilled", "Go Filled"),
    ("Graduate", "Graduate"),
    ("GraduationCap", "Graduation Cap"),
    ("Grid", "Grid"),
    ("GridAlt", "Grid Alt"),
    ("Group", "Group"),
    ("GroupFilled", "Group Filled"),
    ("Groups", "Groups"),
    ("Hamburger", "Hamburger"),
    ("HandBack", "Hand Back"),
    ("HandFront", "Hand Front"),
    ("HandPeace", "Hand Peace"),
    ("HandRaised", "Hand Raised"),
    ("HandRaisedHey", "Hand Raised Hey"),
    ("HandWavingBye", "Hand Waving Bye"),
    ("HapticFeedback", "Haptic Feedback"),
    ("Headphones", "Headphones"),
    ("Health", "Health"),
    ("Heart", "Heart"),
    ("HeartFilled", "Heart Filled"),
    ("HeartFilledXs", "Heart Filled Xs"),
    ("HeartXs", "Heart Xs"),
    ("Help", "Help"),
    ("History", "History"),
    ("HistoryOff", "History Off"),
    ("HistoryOn", "History On"),
    ("HomeAlt", "Home Alt"),
    ("Identity", "Identity"),
    ("IdentityMeSecure", "Identity Me Secure"),
    ("ImageCaption", "Image Caption"),
    ("ImageSquare", "Image Square"),
    ("ImageSquarePictureLibrary", "Image Square Picture Library"),
    ("ImageToText", "Image To Text"),
    ("ImageWide", "Image Wide"),
    ("ImageWideFilled", "Image Wide Filled"),
    ("ImageWidePictureLibrary", "Image Wide Picture Library"),
    ("Images", "Images"),
    ("Info", "Info"),
    ("InfoCircle", "Info Circle"),
    ("Inpaint", "Inpaint"),
    ("InpaintRespond", "Inpaint Respond"),
    ("Inspiration", "Inspiration"),
    ("InspirationFilled", "Inspiration Filled"),
    ("Interactiv", "Interactiv"),
    ("InternalKnowledge", "Internal Knowledge"),
    (
        "InternalKnowledgeOptimizedForCircle",
        "Internal Knowledge Optimized For Circle",
    ),
    ("Invoice", "Invoice"),
    ("Io", "Io"),
    ("JumpToCaption", "Jump To Caption"),
    ("Kettlebell", "Kettlebell"),
    ("Keyboard", "Keyboard"),
    ("KeyboardShortcut", "Keyboard Shortcut"),
    ("Lab", "Lab"),
    ("Language", "Language"),
    ("Latency", "Latency"),
    ("Lifesaver", "Lifesaver"),
    ("LightMode", "Light Mode"),
    ("Lightbulb", "Lightbulb"),
    ("Lightbulb20", "Lightbulb20"),
    ("Lightbulb22", "Lightbulb22"),
    ("Lightbulb22Filled", "Lightbulb22Filled"),
    ("LightbulbGlow", "Lightbulb Glow"),
    ("LinkDisabledBold", "Link Disabled Bold"),
    ("LinkExternalWebsite", "Link External Website"),
    ("LocalServices", "Local Services"),
    ("Lock", "Lock"),
    ("LockKeyHole", "Lock Key Hole"),
    ("Logout", "Logout"),
    ("Loop", "Loop"),
    ("LoopLong", "Loop Long"),
    ("LoopNormal", "Loop Normal"),
    ("LoopShort", "Loop Short"),
    ("LoopXs", "Loop Xs"),
    ("Lotus", "Lotus"),
    ("Love", "Love"),
    ("MagnifyingGlassSearch", "Magnifying Glass Search"),
    ("MagnifyingGlassSmSearch", "Magnifying Glass Sm Search"),
    ("ManageHistory", "Manage History"),
    ("Maps", "Maps"),
    ("MapsAddress", "Maps Address"),
    ("MapsDirections", "Maps Directions"),
    ("MarkerCode", "Marker Code"),
    ("MarkerData", "Marker Data"),
    ("MarkerMultiple", "Marker Multiple"),
    ("MarkerQuote", "Marker Quote"),
    ("Mcp", "Mcp"),
    ("Members", "Members"),
    ("MembersFilled", "Members Filled"),
    ("MemoryFilledSm", "Memory Filled Sm"),
    ("MemoryOffRemember", "Memory Off Remember"),
    ("MemoryOnRemember", "Memory On Remember"),
    ("MemoryWriteSm", "Memory Write Sm"),
    ("Menu", "Menu"),
    ("MenuInverted", "Menu Inverted"),
    ("MenuSidebar", "Menu Sidebar"),
    ("Menubar", "Menubar"),
    ("Messaging", "Messaging"),
    ("Mic", "Mic"),
    ("MicFilled", "Mic Filled"),
    ("MicFilledOff", "Mic Filled Off"),
    ("MicLgDictate", "Mic Lg Dictate"),
    ("MicOff", "Mic Off"),
    ("MinimizeDown", "Minimize Down"),
    ("MinimizeLeft", "Minimize Left"),
    ("MinimizeRight", "Minimize Right"),
    ("MinimizeTop", "Minimize Top"),
    ("Minus", "Minus"),
    ("MinusCircle", "Minus Circle"),
    ("MinusCircleFilled", "Minus Circle Filled"),
    ("Mobile", "Mobile"),
    ("Moon", "Moon"),
    ("MoonSunSystem", "Moon Sun System"),
    ("MoreCircleMenuDots", "More Circle Menu Dots"),
    ("Music", "Music"),
    ("MyGptProfileMe", "My Gpt Profile Me"),
    ("Name", "Name"),
    ("NewsPaper", "News Paper"),
    ("NoTraining", "No Training"),
    ("Nodes", "Nodes"),
    ("Notebook", "Notebook"),
    ("NotebookCheck", "Notebook Check"),
    ("NotebookNarrow", "Notebook Narrow"),
    ("NotebookPencil", "Notebook Pencil"),
    ("Notepad", "Notepad"),
    ("NotificationBell", "Notification Bell"),
    ("NotificationOffBell", "Notification Off Bell"),
    ("Number", "Number"),
    ("Object", "Object"),
    ("On", "On"),
    ("OpenLeft", "Open Left"),
    ("OpenRight", "Open Right"),
    ("OpenaiLogoBold", "Openai Logo Bold"),
    ("OpenaiLogoBoldBoundingBox", "Openai Logo Bold Bounding Box"),
    ("OpenaiLogoRegular", "Openai Logo Regular"),
    (
        "OpenaiLogoRegularBoundingBox",
        "Openai Logo Regular Bounding Box",
    ),
    (
        "OpenaiLogoWebappVariable480",
        "Openai Logo Webapp Variable480",
    ),
    ("Operator", "Operator"),
    ("Order", "Order"),
    ("PageBlank", "Page Blank"),
    ("Paid", "Paid"),
    ("Paperclip", "Paperclip"),
    ("PaperclipAttach", "Paperclip Attach"),
    ("ParentControl", "Parent Control"),
    ("PastedText", "Pasted Text"),
    ("Pause", "Pause"),
    ("PauseCircle", "Pause Circle"),
    ("PauseCircleFilled", "Pause Circle Filled"),
    ("PauseOutline", "Pause Outline"),
    ("PauseSm", "Pause Sm"),
    ("Paw", "Paw"),
    ("Pencil", "Pencil"),
    ("PencilSparkle", "Pencil Sparkle"),
    ("PencilSquare", "Pencil Square"),
    ("Pens", "Pens"),
    ("PhoneMissed", "Phone Missed"),
    ("PhoneRing", "Phone Ring"),
    ("PhoneWaves", "Phone Waves"),
    ("PictureInPicture", "Picture In Picture"),
    ("Pin", "Pin"),
    ("PinFilled", "Pin Filled"),
    ("PinWindow", "Pin Window"),
    ("Plane", "Plane"),
    ("PlantDesk", "Plant Desk"),
    ("Play", "Play"),
    ("PlayCircle", "Play Circle"),
    ("PlayCircleFilled", "Play Circle Filled"),
    ("PlayOutline", "Play Outline"),
    ("PlaySm", "Play Sm"),
    ("PlayTriangle", "Play Triangle"),
    ("Playground", "Playground"),
    ("Plugin", "Plugin"),
    ("PluginPuzzle", "Plugin Puzzle"),
    ("Plus", "Plus"),
    ("Plus14px", "Plus14px"),
    ("PlusCircle", "Plus Circle"),
    ("PlusCircleAdd", "Plus Circle Add"),
    ("PlusCircleFilled", "Plus Circle Filled"),
    ("PlusComposer", "Plus Composer"),
    ("PlusFilled", "Plus Filled"),
    ("PlusLg", "Plus Lg"),
    ("PlusLg18pxAdd", "Plus Lg18px Add"),
    ("PlusSm12px", "Plus Sm12px"),
    ("PlusSquareAdd", "Plus Square Add"),
    ("PopOutWindow", "Pop Out Window"),
    ("PresetDefault", "Preset Default"),
    ("PresetSelected", "Preset Selected"),
    ("PrivacyIntern", "Privacy Intern"),
    ("ProDiamond", "Pro Diamond"),
    ("ProFilledDiamond", "Pro Filled Diamond"),
    ("ProductTag", "Product Tag"),
    ("PullRequestClosed", "Pull Request Closed"),
    ("PullRequestDraft", "Pull Request Draft"),
    ("PullRequestMerged", "Pull Request Merged"),
    ("PullRequestOpen", "Pull Request Open"),
    ("Pulse", "Pulse"),
    ("Question", "Question"),
    ("QuestionMark", "Question Mark"),
    ("QuestionMarkCircle", "Question Mark Circle"),
    ("QuickStart", "Quick Start"),
    ("Quote", "Quote"),
    ("QuoteReplyFilledQuoteXs", "Quote Reply Filled Quote Xs"),
    ("RadioSelected", "Radio Selected"),
    ("ReadingLevel", "Reading Level"),
    ("Record", "Record"),
    ("Regenerate", "Regenerate"),
    ("RegenerateOff", "Regenerate Off"),
    ("RegenerateStar", "Regenerate Star"),
    ("Reload", "Reload"),
    ("RemixMild", "Remix Mild"),
    ("RemixMildXs", "Remix Mild Xs"),
    ("RemixStrong", "Remix Strong"),
    ("RemixSubtle", "Remix Subtle"),
    ("RemoveForeverPermanently", "Remove Forever Permanently"),
    ("RemoveRedEye", "Remove Red Eye"),
    ("Reply", "Reply"),
    ("Report", "Report"),
    ("Resend", "Resend"),
    ("ResetChat", "Reset Chat"),
    ("Resolution1080p", "Resolution1080p"),
    ("Resolution360p", "Resolution360p"),
    ("Resolution480p", "Resolution480p"),
    ("Resolution720p", "Resolution720p"),
    ("RestoreUntrash", "Restore Untrash"),
    ("Rewind", "Rewind"),
    ("Robot", "Robot"),
    ("RobotHead", "Robot Head"),
    ("RobotHeadSad", "Robot Head Sad"),
    ("SavedFilledXs", "Saved Filled Xs"),
    ("SavedXs", "Saved Xs"),
    ("Scales", "Scales"),
    ("Scissor", "Scissor"),
    ("ScissorXs", "Scissor Xs"),
    ("ScreenPosition", "Screen Position"),
    ("Search", "Search"),
    ("SearchConnector", "Search Connector"),
    ("SearchFeed", "Search Feed"),
    ("SearchXs", "Search Xs"),
    ("SelectText", "Select Text"),
    ("Settings", "Settings"),
    ("SettingsCircle", "Settings Circle"),
    ("SettingsCog", "Settings Cog"),
    ("SettingsSlider", "Settings Slider"),
    ("SettingsWrench", "Settings Wrench"),
    ("Share", "Share"),
    ("ShareChat", "Share Chat"),
    ("ShareScreen", "Share Screen"),
    ("ShareScreenFilled", "Share Screen Filled"),
    ("ShareScreenOff", "Share Screen Off"),
    ("ShareScreenOffFilled", "Share Screen Off Filled"),
    ("ShieldCheck", "Shield Check"),
    ("ShieldKey", "Shield Key"),
    ("ShieldLock", "Shield Lock"),
    ("ShieldPerson", "Shield Person"),
    ("ShoppingBag", "Shopping Bag"),
    ("Shortcuts", "Shortcuts"),
    ("Shuffle", "Shuffle"),
    ("Sidebar", "Sidebar"),
    ("SidebarCollapseLeft", "Sidebar Collapse Left"),
    ("SidebarCollapseRight", "Sidebar Collapse Right"),
    ("SidebarFloatingLeft", "Sidebar Floating Left"),
    ("SidebarFloatingOpenLeft", "Sidebar Floating Open Left"),
    ("SidebarFloatingOpenRight", "Sidebar Floating Open Right"),
    ("SidebarFloatingRight", "Sidebar Floating Right"),
    ("SidebarLeft", "Sidebar Left"),
    ("SidebarMenuMobile", "Sidebar Menu Mobile"),
    (
        "SidebarMenuMobileBadgeCutout",
        "Sidebar Menu Mobile Badge Cutout",
    ),
    ("SidebarOpenLeft", "Sidebar Open Left"),
    ("SidebarOpenLeftAlt", "Sidebar Open Left Alt"),
    ("SidebarOpenRight", "Sidebar Open Right"),
    ("SidebarOpenRightAlt", "Sidebar Open Right Alt"),
    ("SidebarRight", "Sidebar Right"),
    ("SimpleRelax", "Simple Relax"),
    ("SimpleSad", "Simple Sad"),
    ("SimpleSmile", "Simple Smile"),
    ("Skip", "Skip"),
    ("Sleep", "Sleep"),
    ("Snorkle", "Snorkle"),
    ("Snowflake", "Snowflake"),
    ("SoraBasicPopcorn", "Sora Basic Popcorn"),
    ("SoraProDirector", "Sora Pro Director"),
    ("SoundOffSimpleMute", "Sound Off Simple Mute"),
    ("SoundOffSpeaker", "Sound Off Speaker"),
    (
        "SoundOnReadOutLoudSpeaker",
        "Sound On Read Out Loud Speaker",
    ),
    ("Sparkle", "Sparkle"),
    ("SparkleDouble", "Sparkle Double"),
    ("SparkleFilledPlus", "Sparkle Filled Plus"),
    ("SparklePlus", "Sparkle Plus"),
    ("Sparkles", "Sparkles"),
    ("SparklesFilled", "Sparkles Filled"),
    ("Speak", "Speak"),
    ("SpeechToText", "Speech To Text"),
    ("Speed", "Speed"),
    ("SpeedometerLatencySpeed", "Speedometer Latency Speed"),
    ("Spelling", "Spelling"),
    ("Spin", "Spin"),
    (
        "SquareCheckCheckboxChecked",
        "Square Check Checkbox Checked",
    ),
    (
        "SquareCheckFilledCheckboxCheckedFilled",
        "Square Check Filled Checkbox Checked Filled",
    ),
    ("SquareCheckboxUnchecked", "Square Checkbox Unchecked"),
    ("SquareCode", "Square Code"),
    ("SquareFilledTableLegend", "Square Filled Table Legend"),
    ("SquareImage", "Square Image"),
    ("SquarePlus", "Square Plus"),
    ("SquarePlusAlt", "Square Plus Alt"),
    ("SquareTableLegend", "Square Table Legend"),
    ("SquareText", "Square Text"),
    ("Stack", "Stack"),
    ("StarFilled", "Star Filled"),
    ("StartStrokeMd", "Start Stroke Md"),
    ("Status", "Status"),
    ("Stethoscope", "Stethoscope"),
    ("StickyNote", "Sticky Note"),
    ("Stop", "Stop"),
    ("StopCircle", "Stop Circle"),
    ("StopCircleFilled", "Stop Circle Filled"),
    ("StopOutline", "Stop Outline"),
    ("StopSm", "Stop Sm"),
    ("StopStrokeMd", "Stop Stroke Md"),
    ("Stopwatch", "Stopwatch"),
    ("Storage", "Storage"),
    ("Storyboard", "Storyboard"),
    ("String", "String"),
    ("Studio", "Studio"),
    ("Stuff", "Stuff"),
    ("StuffTools", "Stuff Tools"),
    ("SubscriptionPlan", "Subscription Plan"),
    ("SuggestEdit", "Suggest Edit"),
    (
        "SuitcaseFilledWorkBusiness",
        "Suitcase Filled Work Business",
    ),
    ("SuitcaseWorkBusiness", "Suitcase Work Business"),
    ("Sun", "Sun"),
    ("SystemMode", "System Mode"),
    ("TBoneRaw", "TBone Raw"),
    ("TableCellFilled", "Table Cell Filled"),
    ("TableCellsFilled", "Table Cells Filled"),
    ("TableColumnFilled", "Table Column Filled"),
    ("TableFilled", "Table Filled"),
    ("TableRowFilled", "Table Row Filled"),
    ("Tap", "Tap"),
    ("Tasks", "Tasks"),
    ("Telescope", "Telescope"),
    ("TerminalLg", "Terminal Lg"),
    ("Terms", "Terms"),
    ("Text", "Text"),
    ("TextLonger", "Text Longer"),
    ("TextPrompt", "Text Prompt"),
    ("TextShorter", "Text Shorter"),
    ("TextShorterConcise", "Text Shorter Concise"),
    ("TextToSpeech", "Text To Speech"),
    ("ThumbDown", "Thumb Down"),
    ("ThumbDownFilled", "Thumb Down Filled"),
    ("ThumbMixed", "Thumb Mixed"),
    ("ThumbUp", "Thumb Up"),
    ("ThumbUpFilled", "Thumb Up Filled"),
    ("ThumbnailLarge", "Thumbnail Large"),
    ("ThumbnailMedium", "Thumbnail Medium"),
    ("ThumbnailSmall", "Thumbnail Small"),
    ("Thumbs", "Thumbs"),
    ("Timer", "Timer"),
    ("Tools", "Tools"),
    ("ToolsSkills", "Tools Skills"),
    ("Translate", "Translate"),
    ("Trash", "Trash"),
    ("TrashRemove", "Trash Remove"),
    ("Trending", "Trending"),
    (
        "TriangleExclamationErrorWarning",
        "Triangle Exclamation Error Warning",
    ),
    (
        "TriangleExclamationFilledErrorWarning",
        "Triangle Exclamation Filled Error Warning",
    ),
    ("TrophyTop", "Trophy Top"),
    ("TuningFork", "Tuning Fork"),
    ("Unarchive", "Unarchive"),
    ("Undo", "Undo"),
    ("Unlink", "Unlink"),
    ("Unpin", "Unpin"),
    ("Upgrade", "Upgrade"),
    ("UpgradePlan", "Upgrade Plan"),
    ("UploadDocuments", "Upload Documents"),
    ("Upscale", "Upscale"),
    ("UpscaleXs", "Upscale Xs"),
    ("Usage", "Usage"),
    ("UserAdd", "User Add"),
    ("UserGpts", "User Gpts"),
    ("UserHeart", "User Heart"),
    ("UserLock", "User Lock"),
    ("UserVoice", "User Voice"),
    ("Users", "Users"),
    ("Variation2v2", "Variation2v2"),
    ("VariationV21", "Variation V21"),
    ("VariationV31", "Variation V31"),
    ("VariationV32", "Variation V32"),
    ("VariationV33", "Variation V33"),
    ("VariationV41", "Variation V41"),
    ("VariationV42", "Variation V42"),
    ("VariationV43", "Variation V43"),
    ("VariationV44", "Variation V44"),
    ("VersionsV1", "Versions V1"),
    ("Video", "Video"),
    ("VideoCaption", "Video Caption"),
    ("VideoFilled", "Video Filled"),
    ("VideoFilledOff", "Video Filled Off"),
    ("VideoGrid", "Video Grid"),
    ("VideoList", "Video List"),
    ("VideoToText", "Video To Text"),
    ("Videos", "Videos"),
    ("Voice", "Voice"),
    ("Voice4Bars", "Voice4Bars"),
    ("Voice5BarsSoundwave", "Voice5Bars Soundwave"),
    ("VoiceBold", "Voice Bold"),
    (
        "VoiceInputAreaMobileFilledVoiceXs",
        "Voice Input Area Mobile Filled Voice Xs",
    ),
    ("VoiceLight", "Voice Light"),
    ("Warning", "Warning"),
    (
        "WarningFilledWrapCenteredForCircle",
        "Warning Filled Wrap Centered For Circle",
    ),
    (
        "WarningWrapCenteredForCircle",
        "Warning Wrap Centered For Circle",
    ),
    ("Wave", "Wave"),
    ("WebsiteNetwork", "Website Network"),
    ("Whisk", "Whisk"),
    ("WhisperAutoSubmit", "Whisper Auto Submit"),
    ("Widget", "Widget"),
    ("WidgetAdd", "Widget Add"),
    ("WorkWithApps", "Work With Apps"),
    ("Workspace", "Workspace"),
    ("Wreath", "Wreath"),
    ("WriteAlt", "Write Alt"),
    ("WriteAlt2", "Write Alt2"),
    ("Writing", "Writing"),
    ("X", "X"),
    ("XCircle", "XCircle"),
    ("XCircleCrossedClose", "XCircle Crossed Close"),
    ("XCircleFilled", "XCircle Filled"),
    ("XCircleFilledCrossedClose", "XCircle Filled Crossed Close"),
    ("XCrossed", "XCrossed"),
    ("XSquareCrossed", "XSquare Crossed"),
    ("XSquareFilledCrossed", "XSquare Filled Crossed"),
    ("XXs", "XXs"),
    ("XXsCrossed", "XXs Crossed"),
];
pub fn choices(query: &str) -> ModelRc<FavoriteIconChoice> {
    let query = query.trim().to_lowercase();
    let limit = if query.is_empty() { 18 } else { 48 };
    Rc::new(VecModel::from(
        KEYS.iter()
            .filter(|(key, label)| {
                query.is_empty()
                    || key.to_lowercase().contains(&query)
                    || label.to_lowercase().contains(&query)
            })
            .take(limit)
            .map(|(key, label)| FavoriteIconChoice {
                key: (*key).into(),
                label: (*label).into(),
            })
            .collect::<Vec<_>>(),
    ))
    .into()
}
#[cfg(test)]
mod tests {
    use super::*;
    use slint::Model;
    #[test]
    fn preserves_full_catalog_and_curated_order() {
        let unique = KEYS
            .iter()
            .map(|(key, _)| *key)
            .collect::<std::collections::HashSet<_>>();
        assert_eq!(unique.len(), KEYS.len());
        assert!(KEYS.len() > 500);
        assert_eq!(KEYS[0].0, "none");
        assert_eq!(KEYS[1].0, "Mail");
        assert_eq!(choices("").row_count(), 18);
        assert!(choices("a").row_count() <= 48);
        assert!(choices("mAiL").iter().any(|r| r.key == "Mail"));
        assert_eq!(choices("__not_an_icon__").row_count(), 0);
    }
}

const SORTED_KEYS: &[&str] = &[
    "AddMember",
    "AddSources",
    "Agent",
    "AgentMode",
    "AllGizmos",
    "AllProductsExplore",
    "Analytics",
    "AnalyzeData",
    "ApiKey",
    "ApiKeyAdmin",
    "ApiKeyServiceAccount",
    "ApiKeys",
    "Archive",
    "Array",
    "ArrowBottomLeftSm",
    "ArrowBottomRightSm",
    "ArrowCurved",
    "ArrowCurvedLeft",
    "ArrowCurvedRight",
    "ArrowCurvedRightXs",
    "ArrowCurvedRightXs24px",
    "ArrowDown",
    "ArrowDownLg",
    "ArrowDownSm",
    "ArrowLeft",
    "ArrowLeftLg",
    "ArrowLeftSm",
    "ArrowRight",
    "ArrowRightLg",
    "ArrowRightSm",
    "ArrowRotateCcw",
    "ArrowRotateCw",
    "ArrowTopLeftSm",
    "ArrowTopRightSm",
    "ArrowUp",
    "ArrowUpLg",
    "ArrowUpRight",
    "ArrowUpSm",
    "AspectRatio11",
    "AspectRatio169",
    "AspectRatio34",
    "AspectRatio43",
    "AspectRatio916",
    "Assistant",
    "Astronout",
    "AtSign",
    "Atom",
    "AutoPairApps",
    "AutoSuggestedEdits",
    "Autocomplete",
    "AvatarFilledProfile",
    "AvatarProfile",
    "Back10s",
    "Back15s",
    "BackLarge",
    "BackSmall",
    "BackToApp",
    "BackgroundConversation",
    "BalancingScale",
    "BarChart",
    "BarChartFilled",
    "Batch",
    "Batches",
    "Bell",
    "BellFilled",
    "Beta",
    "Bills",
    "Blend",
    "BlendingCurveSharp",
    "BlendingCurveSmooth",
    "BlendingCurveSubtle",
    "Bolt",
    "Book",
    "BookBookmark",
    "BookClock",
    "BookClosed",
    "BookOpen",
    "BookWrench",
    "Boolean",
    "Brain",
    "Branch",
    "BranchAlt",
    "Bug",
    "BuilderProfileCard",
    "BuildingWorkspace",
    "Business",
    "BusinessFilled",
    "Cabinet",
    "Calendar",
    "CalendarAlt",
    "CalendarToday",
    "Camera",
    "CameraFilledPhoto",
    "CameraPhoto",
    "CaptionCcOff",
    "CaptionCcOn",
    "CaptionOff",
    "CaptionOn",
    "Card",
    "CaretDown",
    "CaretLeft",
    "CaretRight",
    "CaretUp",
    "Category",
    "Certificate",
    "Chart",
    "ChartXAxis",
    "ChartYAxis",
    "Chat",
    "ChatCompose",
    "ChatDashedCheckedTemp",
    "ChatDashedTemp",
    "ChatTemporary",
    "ChatTripleDots",
    "Chats",
    "Check",
    "CheckCircle",
    "CheckCircleDashed",
    "CheckCircleFilled",
    "CheckLg",
    "CheckMd",
    "ChevronDown",
    "ChevronDownLg",
    "ChevronDownMd",
    "ChevronDownUp",
    "ChevronDownVector",
    "ChevronLeft",
    "ChevronLeftLg",
    "ChevronLeftMd",
    "ChevronRight",
    "ChevronRightAlt",
    "ChevronRightLg",
    "ChevronRightMd",
    "ChevronSmallDown",
    "ChevronSmallLeft",
    "ChevronSmallRight",
    "ChevronSmallUp",
    "ChevronUp",
    "ChevronUpDown",
    "ChevronUpLg",
    "ChevronUpMd",
    "Circle",
    "CircleDashed",
    "CircleQuestion",
    "ClappingBoardClosed",
    "ClappingBoardOpen",
    "Cleanup",
    "Clear",
    "Click",
    "Clip",
    "Clipboard",
    "ClipboardCopy",
    "Clock",
    "Clock10s",
    "Clock15s",
    "Clock20s",
    "Clock5s",
    "ClockOff",
    "CloseBold",
    "Code",
    "CodeSquareSlash",
    "Collapse",
    "CollapseLarge",
    "CollapseLeft",
    "CollapseLg",
    "CollapseRight",
    "CollapseSm",
    "CollapseSmall",
    "ColorTheme",
    "Comment",
    "Commit",
    "Compare",
    "CompareArrows",
    "Compass",
    "Complete",
    "ComposeCanvasEditStar",
    "ComposeDashedTemporary",
    "ComposeEditSquare",
    "Confetti",
    "ConfettiParty",
    "Connect",
    "ConnectApps",
    "ConnectedDynamicGpt",
    "ConnectorsConnectedApps",
    "Copy",
    "CreditCard",
    "Credits",
    "Cube",
    "Cursor",
    "Customize",
    "DarkMode",
    "DataControls",
    "DeepSearchTelescope",
    "Delete",
    "DeleteAccount",
    "Desktop",
    "DiningEvents",
    "DisabledCursor",
    "Dock",
    "Document",
    "Documentation",
    "DollarCircle",
    "Dot",
    "DotsHorizontal",
    "DotsHorizontalCircle",
    "DotsHorizontalMoreMenu",
    "DotsVertical",
    "DotsVerticalCircle",
    "DotsVerticalMoreMenu",
    "DoubleChevronLeft",
    "DoubleChevronRight",
    "Download",
    "DownloadCircle",
    "DownloadGifWatermark",
    "DownloadSimple",
    "DownloadVideo",
    "DownloadVideoWatermark",
    "Dropdown",
    "DropdownVector",
    "Dumbbell",
    "EarthTravelWorld",
    "Edit",
    "EditAlt",
    "EditDalleImage",
    "EditPencil",
    "EditStar",
    "EditXs",
    "Education",
    "Email",
    "EmojiAdd",
    "EmojiLists",
    "EmojiRemove",
    "EmojiSections",
    "EmojiWords",
    "EmptyCircle",
    "EmptyCircleFilled",
    "EnterLogin",
    "Enum",
    "Equal",
    "Error",
    "ExclamationMarkCircle",
    "ExitLogout",
    "Expand",
    "ExpandLarge",
    "ExpandLg",
    "ExpandMd",
    "ExpandSm",
    "ExpandSmall",
    "Explore",
    "ExploreSora",
    "ExternalLink",
    "Eye",
    "EyeClosed",
    "EyeOff",
    "FeaturedWreath",
    "File",
    "File3d",
    "FileAudio",
    "FileBlank",
    "FileCode",
    "FileDocument",
    "FileImage",
    "FilePresentation",
    "FileSpreadsheet",
    "FileSpreedsheet",
    "FileUpload",
    "FileVideo",
    "FileZip",
    "Filter",
    "FineTuning",
    "FistBump",
    "Flag",
    "Flash",
    "Flask",
    "FlaskFilled",
    "Folder",
    "FolderDocumentsFinder",
    "FolderOpen",
    "FolderPlus",
    "FolderPlusAdd",
    "FolderShared",
    "FolderSharedOpen",
    "FolderStuffed",
    "FolderUnshare",
    "Folders",
    "Followup",
    "Forum",
    "Forward",
    "Forward10s",
    "Forward15s",
    "Frozen",
    "Function",
    "Functions",
    "GenerateSuggestedEdits",
    "Glasses",
    "Globe",
    "GlobeAltRealTimeSearch",
    "GlobeFilled",
    "GlobeOffRealTimeSearch",
    "GlobeRealTimeSearch",
    "GlobeSpin",
    "Go",
    "GoFilled",
    "Graduate",
    "GraduationCap",
    "Grid",
    "GridAlt",
    "Group",
    "GroupFilled",
    "Groups",
    "Hamburger",
    "HandBack",
    "HandFront",
    "HandPeace",
    "HandRaised",
    "HandRaisedHey",
    "HandWavingBye",
    "HapticFeedback",
    "Headphones",
    "Health",
    "Heart",
    "HeartFilled",
    "HeartFilledXs",
    "HeartXs",
    "Help",
    "History",
    "HistoryOff",
    "HistoryOn",
    "Home",
    "HomeAlt",
    "Identity",
    "IdentityMeSecure",
    "ImageCaption",
    "ImageSquare",
    "ImageSquarePictureLibrary",
    "ImageToText",
    "ImageWide",
    "ImageWideFilled",
    "ImageWidePictureLibrary",
    "Images",
    "Info",
    "InfoCircle",
    "Inpaint",
    "InpaintRespond",
    "Inspiration",
    "InspirationFilled",
    "Interactiv",
    "InternalKnowledge",
    "InternalKnowledgeOptimizedForCircle",
    "Invoice",
    "Io",
    "JumpToCaption",
    "Kettlebell",
    "Key",
    "Keyboard",
    "KeyboardShortcut",
    "Lab",
    "Language",
    "Latency",
    "Lifesaver",
    "LightMode",
    "Lightbulb",
    "Lightbulb20",
    "Lightbulb22",
    "Lightbulb22Filled",
    "LightbulbGlow",
    "Link",
    "LinkDisabledBold",
    "LinkExternalWebsite",
    "LocalServices",
    "Lock",
    "LockKeyHole",
    "Logout",
    "Loop",
    "LoopLong",
    "LoopNormal",
    "LoopShort",
    "LoopXs",
    "Lotus",
    "Love",
    "MagnifyingGlassSearch",
    "MagnifyingGlassSmSearch",
    "Mail",
    "ManageHistory",
    "MapPin",
    "Maps",
    "MapsAddress",
    "MapsDirections",
    "MarkerCode",
    "MarkerData",
    "MarkerMultiple",
    "MarkerQuote",
    "Mcp",
    "Members",
    "MembersFilled",
    "MemoryFilledSm",
    "MemoryOffRemember",
    "MemoryOnRemember",
    "MemoryWriteSm",
    "Menu",
    "MenuInverted",
    "MenuSidebar",
    "Menubar",
    "Messaging",
    "Mic",
    "MicFilled",
    "MicFilledOff",
    "MicLgDictate",
    "MicOff",
    "MinimizeDown",
    "MinimizeLeft",
    "MinimizeRight",
    "MinimizeTop",
    "Minus",
    "MinusCircle",
    "MinusCircleFilled",
    "Mobile",
    "Moon",
    "MoonSunSystem",
    "MoreCircleMenuDots",
    "Music",
    "MyGptProfileMe",
    "Name",
    "NewsPaper",
    "NoTraining",
    "Nodes",
    "Notebook",
    "NotebookCheck",
    "NotebookNarrow",
    "NotebookPencil",
    "Notepad",
    "NotificationBell",
    "NotificationOffBell",
    "Number",
    "Object",
    "On",
    "OpenLeft",
    "OpenRight",
    "OpenaiLogoBold",
    "OpenaiLogoBoldBoundingBox",
    "OpenaiLogoRegular",
    "OpenaiLogoRegularBoundingBox",
    "OpenaiLogoWebappVariable480",
    "Operator",
    "Order",
    "PageBlank",
    "Paid",
    "Paperclip",
    "PaperclipAttach",
    "ParentControl",
    "PastedText",
    "Pause",
    "PauseCircle",
    "PauseCircleFilled",
    "PauseOutline",
    "PauseSm",
    "Paw",
    "Pencil",
    "PencilSparkle",
    "PencilSquare",
    "Pens",
    "Phone",
    "PhoneMissed",
    "PhoneRing",
    "PhoneWaves",
    "PictureInPicture",
    "Pin",
    "PinFilled",
    "PinWindow",
    "Plane",
    "PlantDesk",
    "Play",
    "PlayCircle",
    "PlayCircleFilled",
    "PlayOutline",
    "PlaySm",
    "PlayTriangle",
    "Playground",
    "Plugin",
    "PluginPuzzle",
    "Plus",
    "Plus14px",
    "PlusCircle",
    "PlusCircleAdd",
    "PlusCircleFilled",
    "PlusComposer",
    "PlusFilled",
    "PlusLg",
    "PlusLg18pxAdd",
    "PlusSm12px",
    "PlusSquareAdd",
    "PopOutWindow",
    "PresetDefault",
    "PresetSelected",
    "PrivacyIntern",
    "ProDiamond",
    "ProFilledDiamond",
    "ProductTag",
    "PullRequestClosed",
    "PullRequestDraft",
    "PullRequestMerged",
    "PullRequestOpen",
    "Pulse",
    "Question",
    "QuestionMark",
    "QuestionMarkCircle",
    "QuickStart",
    "Quote",
    "QuoteReplyFilledQuoteXs",
    "RadioSelected",
    "ReadingLevel",
    "Record",
    "Regenerate",
    "RegenerateOff",
    "RegenerateStar",
    "Reload",
    "RemixMild",
    "RemixMildXs",
    "RemixStrong",
    "RemixSubtle",
    "RemoveForeverPermanently",
    "RemoveRedEye",
    "Reply",
    "Report",
    "Resend",
    "ResetChat",
    "Resolution1080p",
    "Resolution360p",
    "Resolution480p",
    "Resolution720p",
    "RestoreUntrash",
    "Rewind",
    "Robot",
    "RobotHead",
    "RobotHeadSad",
    "SavedFilledXs",
    "SavedXs",
    "Scales",
    "Scissor",
    "ScissorXs",
    "ScreenPosition",
    "Search",
    "SearchConnector",
    "SearchFeed",
    "SearchXs",
    "SelectText",
    "Settings",
    "SettingsCircle",
    "SettingsCog",
    "SettingsSlider",
    "SettingsWrench",
    "Share",
    "ShareChat",
    "ShareScreen",
    "ShareScreenFilled",
    "ShareScreenOff",
    "ShareScreenOffFilled",
    "ShieldCheck",
    "ShieldKey",
    "ShieldLock",
    "ShieldPerson",
    "ShoppingBag",
    "Shortcuts",
    "Shuffle",
    "Sidebar",
    "SidebarCollapseLeft",
    "SidebarCollapseRight",
    "SidebarFloatingLeft",
    "SidebarFloatingOpenLeft",
    "SidebarFloatingOpenRight",
    "SidebarFloatingRight",
    "SidebarLeft",
    "SidebarMenuMobile",
    "SidebarMenuMobileBadgeCutout",
    "SidebarOpenLeft",
    "SidebarOpenLeftAlt",
    "SidebarOpenRight",
    "SidebarOpenRightAlt",
    "SidebarRight",
    "SimpleRelax",
    "SimpleSad",
    "SimpleSmile",
    "Skip",
    "Sleep",
    "Snorkle",
    "Snowflake",
    "SoraBasicPopcorn",
    "SoraProDirector",
    "SoundOffSimpleMute",
    "SoundOffSpeaker",
    "SoundOnReadOutLoudSpeaker",
    "Sparkle",
    "SparkleDouble",
    "SparkleFilledPlus",
    "SparklePlus",
    "Sparkles",
    "SparklesFilled",
    "Speak",
    "SpeechToText",
    "Speed",
    "SpeedometerLatencySpeed",
    "Spelling",
    "Spin",
    "SquareCheckCheckboxChecked",
    "SquareCheckFilledCheckboxCheckedFilled",
    "SquareCheckboxUnchecked",
    "SquareCode",
    "SquareFilledTableLegend",
    "SquareImage",
    "SquarePlus",
    "SquarePlusAlt",
    "SquareTableLegend",
    "SquareText",
    "Stack",
    "Star",
    "StarFilled",
    "StartStrokeMd",
    "Status",
    "Stethoscope",
    "StickyNote",
    "Stop",
    "StopCircle",
    "StopCircleFilled",
    "StopOutline",
    "StopSm",
    "StopStrokeMd",
    "Stopwatch",
    "Storage",
    "Storyboard",
    "String",
    "Studio",
    "Stuff",
    "StuffTools",
    "SubscriptionPlan",
    "SuggestEdit",
    "Suitcase",
    "SuitcaseFilledWorkBusiness",
    "SuitcaseWorkBusiness",
    "Sun",
    "SystemMode",
    "TBoneRaw",
    "TableCellFilled",
    "TableCellsFilled",
    "TableColumnFilled",
    "TableFilled",
    "TableRowFilled",
    "Tag",
    "Tap",
    "Tasks",
    "Telescope",
    "Terminal",
    "TerminalLg",
    "Terms",
    "Text",
    "TextLonger",
    "TextPrompt",
    "TextShorter",
    "TextShorterConcise",
    "TextToSpeech",
    "ThumbDown",
    "ThumbDownFilled",
    "ThumbMixed",
    "ThumbUp",
    "ThumbUpFilled",
    "ThumbnailLarge",
    "ThumbnailMedium",
    "ThumbnailSmall",
    "Thumbs",
    "Timer",
    "Tools",
    "ToolsSkills",
    "Translate",
    "Trash",
    "TrashRemove",
    "Trending",
    "TriangleExclamationErrorWarning",
    "TriangleExclamationFilledErrorWarning",
    "TrophyTop",
    "TuningFork",
    "Unarchive",
    "Undo",
    "Unlink",
    "Unpin",
    "Upgrade",
    "UpgradePlan",
    "UploadDocuments",
    "Upscale",
    "UpscaleXs",
    "Usage",
    "User",
    "UserAdd",
    "UserGpts",
    "UserHeart",
    "UserLock",
    "UserVoice",
    "Users",
    "Variation2v2",
    "VariationV21",
    "VariationV31",
    "VariationV32",
    "VariationV33",
    "VariationV41",
    "VariationV42",
    "VariationV43",
    "VariationV44",
    "VersionsV1",
    "Video",
    "VideoCaption",
    "VideoFilled",
    "VideoFilledOff",
    "VideoGrid",
    "VideoList",
    "VideoToText",
    "Videos",
    "Voice",
    "Voice4Bars",
    "Voice5BarsSoundwave",
    "VoiceBold",
    "VoiceInputAreaMobileFilledVoiceXs",
    "VoiceLight",
    "Warning",
    "WarningFilledWrapCenteredForCircle",
    "WarningWrapCenteredForCircle",
    "Wave",
    "WebsiteNetwork",
    "Whisk",
    "WhisperAutoSubmit",
    "Widget",
    "WidgetAdd",
    "WorkWithApps",
    "Workspace",
    "Wreath",
    "WriteAlt",
    "WriteAlt2",
    "Writing",
    "X",
    "XCircle",
    "XCircleCrossedClose",
    "XCircleFilled",
    "XCircleFilledCrossedClose",
    "XCrossed",
    "XSquareCrossed",
    "XSquareFilledCrossed",
    "XXs",
    "XXsCrossed",
];
pub fn index(key: &str) -> i32 {
    SORTED_KEYS
        .binary_search(&key)
        .map(|n| n as i32)
        .unwrap_or(-1)
}
